# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(898, 841)
        self.button1 = QtWidgets.QPushButton(form)
        self.button1.setGeometry(QtCore.QRect(690, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.textedit1 = QtWidgets.QLineEdit(form)
        self.textedit1.setGeometry(QtCore.QRect(30, 20, 581, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        self.textedit1.setFont(font)
        self.textedit1.setObjectName("textedit1")
        self.label1 = QtWidgets.QLabel(form)
        self.label1.setGeometry(QtCore.QRect(30, 90, 831, 261))
        self.label1.setAutoFillBackground(False)
        self.label1.setFrameShape(QtWidgets.QFrame.Panel)
        self.label1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(form)
        self.label2.setGeometry(QtCore.QRect(30, 370, 341, 441))
        self.label2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.button2 = QtWidgets.QPushButton(form)
        self.button2.setGeometry(QtCore.QRect(400, 400, 93, 91))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        self.label3 = QtWidgets.QLabel(form)
        self.label3.setGeometry(QtCore.QRect(520, 370, 341, 441))
        self.label3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.button3 = QtWidgets.QPushButton(form)
        self.button3.setGeometry(QtCore.QRect(400, 550, 93, 91))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        self.button3.setFont(font)
        self.button3.setObjectName("button3")
        self.button4 = QtWidgets.QPushButton(form)
        self.button4.setGeometry(QtCore.QRect(400, 700, 93, 91))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(10)
        self.button4.setFont(font)
        self.button4.setObjectName("button4")

        self.retranslateUi(form)
        self.button1.clicked.connect(form.showtext) # type: ignore
        self.button1.clicked.connect(form.showpicture) # type: ignore
        self.button2.clicked.connect(form.blur) # type: ignore
        self.button4.clicked.connect(form.edge) # type: ignore
        self.button3.clicked.connect(form.gray) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "豆瓣TOP250电影排行榜查询器"))
        self.button1.setText(_translate("form", "查询"))
        self.textedit1.setPlaceholderText(_translate("form", "请输入您要查询的电影排名（1-250）"))
        self.button2.setText(_translate("form", "模糊"))
        self.button3.setText(_translate("form", "灰度"))
        self.button4.setText(_translate("form", "轮廓"))
